version: "3.8"

services:
  erpegobotek:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: ["python", "erpegobotek/bot/discord"]
